In [1]:
import numpy as np

In [3]:
x = np.arange(0.10, 5); print(f"x shape: {x.shape}"); print(x)

x shape: (5,)
[0.1 1.1 2.1 3.1 4.1]


In [4]:
x = np.random.rand(4); print(x)

[1.39052497e-01 4.11696795e-05 4.20785386e-01 8.80347439e-01]


In [7]:
np.random.random_sample((2,3,3))

array([[[0.13833549, 0.65788601, 0.49233987],
        [0.15623924, 0.36099583, 0.62535744],
        [0.23810243, 0.4763333 , 0.50862991]],

       [[0.97355741, 0.41590596, 0.21543867],
        [0.22946903, 0.99441125, 0.20269512],
        [0.9306899 , 0.23406717, 0.24394902]]])